version: '3.5'

services:
  mailman:
    image: avillalba96/docker-mailman:1.1
    restart: unless-stopped
    container_name: smtp1.example.com.ar
    hostname: smtp1.example.com.ar
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    - ./mailman-cfg/etc/mailman/:/etc/mailman/
    - ./mailman-cfg/lib/mailman:/var/lib/mailman
    environment:
    - MAILMAN_URLHOST=www.example.com #mailmanurl:8080
    - MAILMAN_EMAILHOST=example.com #postfixdomain
    - MAILMAN_ADMINMAIL=admin@example.com #useradm
    - MAILMAN_ADMINPASS=password #userpass
    - MAILMAN_LANGUAGE=en #mailmanlanguage
    ports:
    - "80:80"
    - "2525:25"
